# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations

      class CreateSessionTokenFromTemplateRequest
        
        include Crystalline::MetadataFields

        # The ID of the session
        field :session_id, ::String, { 'path_param': { 'field_name': 'session_id', 'style': 'simple', 'explode': false } }
        # The name of the JWT template defined in your instance (e.g. `custom_hasura`).
        field :template_name, ::String, { 'path_param': { 'field_name': 'template_name', 'style': 'simple', 'explode': false } }

        field :body, Crystalline::Nilable.new(Models::Operations::CreateSessionTokenFromTemplateRequestBody), { 'request': { 'media_type': 'application/json' } }

        
        def initialize(session_id:, template_name:, body: nil)
          @session_id = session_id
          @template_name = template_name
          @body = body
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @session_id == other.session_id
          return false unless @template_name == other.template_name
          return false unless @body == other.body
          true
        end
      end
    end
  end
end
