# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations

      class CreateSCIMDirectoryRequest
        
        include Crystalline::MetadataFields

        # The ID of the enterprise connection to associate with this SCIM directory.
        field :enterprise_connection_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('enterprise_connection_id'), required: true } }
        # The identity provider for this SCIM directory.
        field :provider, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('provider'), required: true } }
        # A human-friendly name for the SCIM directory.
        field :name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('name') } }
        # Optional SCIM group to organization role mappings to create with the directory.
        field :group_role_mappings, Crystalline::Nilable.new(Crystalline::Array.new(Models::Operations::GroupRoleMapping)), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('group_role_mappings') } }

        
        def initialize(enterprise_connection_id:, provider:, name: nil, group_role_mappings: nil)
          @enterprise_connection_id = enterprise_connection_id
          @provider = provider
          @name = name
          @group_role_mappings = group_role_mappings
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @enterprise_connection_id == other.enterprise_connection_id
          return false unless @provider == other.provider
          return false unless @name == other.name
          return false unless @group_role_mappings == other.group_role_mappings
          true
        end
      end
    end
  end
end
