# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations

      class CreateSCIMDirectoryGroupRoleMapping
        
        include Crystalline::MetadataFields

        # The SCIM group ID from the identity provider.
        field :scim_group_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('scim_group_id'), required: true } }
        # The organization role ID to assign to members of the SCIM group.
        field :role_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('role_id'), required: true } }
        # Optional display name for the SCIM group.
        field :scim_group_display_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('scim_group_display_name') } }
        # The precedence for this mapping. If omitted, precedence is assigned by array order.
        field :precedence, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('precedence') } }

        
        def initialize(scim_group_id:, role_id:, scim_group_display_name: nil, precedence: nil)
          @scim_group_id = scim_group_id
          @role_id = role_id
          @scim_group_display_name = scim_group_display_name
          @precedence = precedence
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @scim_group_id == other.scim_group_id
          return false unless @role_id == other.role_id
          return false unless @scim_group_display_name == other.scim_group_display_name
          return false unless @precedence == other.precedence
          true
        end
      end
    end
  end
end
