# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations
      # CreateSAMLConnectionMode1 - Controls the login_hint sent to the IdP on SSO sign-in
      class CreateSAMLConnectionMode1
        include ::Crystalline::Enum
        enums do
          EMAIL_ADDRESS = new('email_address')
          CUSTOM_ATTRIBUTE = new('custom_attribute')
          OFF = new('off')
        end
      end
    end
  end
end
