# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations
      # SAML connection-specific properties. Only applied when the enterprise connection uses SAML (e.g. provider is saml_custom).
      # Use this to set IdP configuration, attribute mapping, and other SAML-specific settings at creation time.
      class CreateEnterpriseConnectionSaml
        
        include Crystalline::MetadataFields

        # IdP entity ID
        field :idp_entity_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('idp_entity_id') } }
        # IdP SSO URL
        field :idp_sso_url, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('idp_sso_url') } }
        # IdP certificate (PEM)
        field :idp_certificate, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('idp_certificate') } }
        # URL to IdP metadata
        field :idp_metadata_url, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('idp_metadata_url') } }
        # Raw IdP metadata XML
        field :idp_metadata, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('idp_metadata') } }
        # Attribute mapping for SAML attributes
        field :attribute_mapping, Crystalline::Nilable.new(Models::Operations::CreateEnterpriseConnectionAttributeMapping), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('attribute_mapping') } }

        field :allow_subdomains, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('allow_subdomains') } }

        field :allow_idp_initiated, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('allow_idp_initiated') } }

        field :force_authn, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('force_authn') } }

        
        def initialize(idp_entity_id: nil, idp_sso_url: nil, idp_certificate: nil, idp_metadata_url: nil, idp_metadata: nil, attribute_mapping: nil, allow_subdomains: nil, allow_idp_initiated: nil, force_authn: nil)
          @idp_entity_id = idp_entity_id
          @idp_sso_url = idp_sso_url
          @idp_certificate = idp_certificate
          @idp_metadata_url = idp_metadata_url
          @idp_metadata = idp_metadata
          @attribute_mapping = attribute_mapping
          @allow_subdomains = allow_subdomains
          @allow_idp_initiated = allow_idp_initiated
          @force_authn = force_authn
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @idp_entity_id == other.idp_entity_id
          return false unless @idp_sso_url == other.idp_sso_url
          return false unless @idp_certificate == other.idp_certificate
          return false unless @idp_metadata_url == other.idp_metadata_url
          return false unless @idp_metadata == other.idp_metadata
          return false unless @attribute_mapping == other.attribute_mapping
          return false unless @allow_subdomains == other.allow_subdomains
          return false unless @allow_idp_initiated == other.allow_idp_initiated
          return false unless @force_authn == other.force_authn
          true
        end
      end
    end
  end
end
