# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations

      class CreateEnterpriseConnectionCustomAttribute
        
        include Crystalline::MetadataFields

        # Display name for the custom attribute
        field :name, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('name'), required: true } }
        # Key used to store the attribute in the user's metadata
        field :key, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('key'), required: true } }
        # Path to extract the attribute value from SSO claims
        field :sso_path, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('sso_path') } }
        # GJSON path to extract the attribute value from SCIM user resources
        field :scim_path, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('scim_path') } }

        
        def initialize(name:, key:, sso_path: nil, scim_path: nil)
          @name = name
          @key = key
          @sso_path = sso_path
          @scim_path = scim_path
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @name == other.name
          return false unless @key == other.key
          return false unless @sso_path == other.sso_path
          return false unless @scim_path == other.scim_path
          true
        end
      end
    end
  end
end
