# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations
      # CreateEnterpriseConnectionProvider - The identity provider (e.g. saml_custom, oidc_custom, oidc_github_enterprise, oidc_gitlab)
      class CreateEnterpriseConnectionProvider
        include ::Crystalline::Enum
        enums do
          SAML_CUSTOM = new('saml_custom')
          SAML_OKTA = new('saml_okta')
          SAML_GOOGLE = new('saml_google')
          SAML_MICROSOFT = new('saml_microsoft')
          OIDC_CUSTOM = new('oidc_custom')
          OIDC_GITHUB_ENTERPRISE = new('oidc_github_enterprise')
          OIDC_GITLAB = new('oidc_gitlab')
        end
      end
    end
  end
end
