# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations

      class CreateDirectoryGroupRoleMapping
        
        include Crystalline::MetadataFields

        # The organization role ID to assign to members of the group.
        field :role_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('role_id'), required: true } }
        # The group ID from the identity provider. Exactly one of `directory_group_id` or `scim_group_id` is required.
        field :directory_group_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('directory_group_id') } }
        # The legacy name for `directory_group_id`. Send either one, or both with the same value; sending both with different values is rejected.
        field :scim_group_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('scim_group_id') } }
        # Optional display name for the group.
        field :directory_group_display_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('directory_group_display_name') } }
        # The legacy name for `directory_group_display_name`. Send either one, or both with the same value; sending both with different values is rejected.
        field :scim_group_display_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('scim_group_display_name') } }
        # The precedence for this mapping. If omitted, precedence is assigned by array order.
        field :precedence, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('precedence') } }

        
        def initialize(role_id:, directory_group_id: nil, scim_group_id: nil, directory_group_display_name: nil, scim_group_display_name: nil, precedence: nil)
          @role_id = role_id
          @directory_group_id = directory_group_id
          @scim_group_id = scim_group_id
          @directory_group_display_name = directory_group_display_name
          @scim_group_display_name = scim_group_display_name
          @precedence = precedence
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @role_id == other.role_id
          return false unless @directory_group_id == other.directory_group_id
          return false unless @scim_group_id == other.scim_group_id
          return false unless @directory_group_display_name == other.directory_group_display_name
          return false unless @scim_group_display_name == other.scim_group_display_name
          return false unless @precedence == other.precedence
          true
        end
      end
    end
  end
end
