# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations
    

      class DeleteDomainRequest
        
        include Crystalline::MetadataFields

        # The ID of the domain that will be deleted. Must be a satellite domain.
        field :domain_id, ::String, { 'path_param': { 'field_name': 'domain_id', 'style': 'simple', 'explode': false } }

        
        def initialize(domain_id:)
          @domain_id = domain_id
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @domain_id == other.domain_id
          true
        end
      end
    end
  end
end
