# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations

      class DeleteSAMLConnectionRequest
        
        include Crystalline::MetadataFields

        # The ID of the SAML Connection to delete
        field :saml_connection_id, ::String, { 'path_param': { 'field_name': 'saml_connection_id', 'style': 'simple', 'explode': false } }

        
        def initialize(saml_connection_id:)
          @saml_connection_id = saml_connection_id
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @saml_connection_id == other.saml_connection_id
          true
        end
      end
    end
  end
end
