# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations
      # GetCommerceSubscriptionItemListStatus - Filter subscription items by status
      class GetCommerceSubscriptionItemListStatus
        include ::Crystalline::Enum
        enums do
          ACTIVE = new('active')
          ENDED = new('ended')
          PAST_DUE = new('past_due')
          UPCOMING = new('upcoming')
          FREE_TRIAL = new('free_trial')
        end
      end
    end
  end
end
