# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations

      class GetPhoneNumberRequest
        
        include Crystalline::MetadataFields

        # The ID of the phone number to retrieve
        field :phone_number_id, ::String, { 'path_param': { 'field_name': 'phone_number_id', 'style': 'simple', 'explode': false } }

        
        def initialize(phone_number_id:)
          @phone_number_id = phone_number_id
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @phone_number_id == other.phone_number_id
          true
        end
      end
    end
  end
end
