# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations
    

      class GetTemplateRequest
        
        include Crystalline::MetadataFields

        # The type of templates to retrieve (email or SMS)
        field :template_type, Models::Operations::GetTemplateTemplateType, { 'path_param': { 'field_name': 'template_type', 'style': 'simple', 'explode': false } }
        # The slug (i.e. machine-friendly name) of the template to retrieve
        field :slug, ::String, { 'path_param': { 'field_name': 'slug', 'style': 'simple', 'explode': false } }

        
        def initialize(template_type:, slug:)
          @template_type = template_type
          @slug = slug
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @template_type == other.template_type
          return false unless @slug == other.slug
          true
        end
      end
    end
  end
end
