# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations
    

      class ListAllowlistIdentifiersRequest
        
        include Crystalline::MetadataFields

        # Whether to paginate the results.
        # If true, the results will be paginated.
        # If false, the results will not be paginated.
        field :paginated, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'query_param': { 'field_name': 'paginated', 'style': 'form', 'explode': true } }
        # Applies a limit to the number of results returned.
        # Can be used for paginating the results together with `offset`.
        field :limit, Crystalline::Nilable.new(::Integer), { 'query_param': { 'field_name': 'limit', 'style': 'form', 'explode': true } }
        # Skip the first `offset` results when paginating.
        # Needs to be an integer greater or equal to zero.
        # To be used in conjunction with `limit`.
        field :offset, Crystalline::Nilable.new(::Integer), { 'query_param': { 'field_name': 'offset', 'style': 'form', 'explode': true } }

        
        def initialize(paginated: nil, limit: 10, offset: 0)
          @paginated = paginated
          @limit = limit
          @offset = offset
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @paginated == other.paginated
          return false unless @limit == other.limit
          return false unless @offset == other.offset
          true
        end
      end
    end
  end
end
