# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations
    

      class ListOAuthApplicationsResponse
        
        include Crystalline::MetadataFields

        # HTTP response content type for this operation
        field :content_type, ::String
        # HTTP response status code for this operation
        field :status_code, ::Integer
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, ::Faraday::Response
        # A list of OAuth applications
        field :o_auth_applications, Crystalline::Nilable.new(Models::Components::OAuthApplications)

        
        def initialize(content_type:, status_code:, raw_response:, o_auth_applications: nil)
          @content_type = content_type
          @status_code = status_code
          @raw_response = raw_response
          @o_auth_applications = o_auth_applications
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @content_type == other.content_type
          return false unless @status_code == other.status_code
          return false unless @raw_response == other.raw_response
          return false unless @o_auth_applications == other.o_auth_applications
          true
        end
      end
    end
  end
end
