# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations

      class ListEnterpriseConnectionTestRunsRequest
        
        include Crystalline::MetadataFields

        # The ID of the enterprise connection
        field :enterprise_connection_id, ::String, { 'path_param': { 'field_name': 'enterprise_connection_id', 'style': 'simple', 'explode': false } }
        # Filter test runs by status (may be repeated)
        field :status, Crystalline::Nilable.new(Crystalline::Array.new(Models::Operations::ListEnterpriseConnectionTestRunsStatus)), { 'query_param': { 'field_name': 'status', 'style': 'form', 'explode': true } }
        # Applies a limit to the number of results returned.
        # Can be used for paginating the results together with `offset`.
        field :limit, Crystalline::Nilable.new(::Integer), { 'query_param': { 'field_name': 'limit', 'style': 'form', 'explode': true } }
        # Skip the first `offset` results when paginating.
        # Needs to be an integer greater or equal to zero.
        # To be used in conjunction with `limit`.
        field :offset, Crystalline::Nilable.new(::Integer), { 'query_param': { 'field_name': 'offset', 'style': 'form', 'explode': true } }

        
        def initialize(enterprise_connection_id:, status: nil, limit: 10, offset: 0)
          @enterprise_connection_id = enterprise_connection_id
          @status = status
          @limit = limit
          @offset = offset
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @enterprise_connection_id == other.enterprise_connection_id
          return false unless @status == other.status
          return false unless @limit == other.limit
          return false unless @offset == other.offset
          true
        end
      end
    end
  end
end
