# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations
    

      class ListSAMLConnectionsRequest
        
        include Crystalline::MetadataFields

        # Returns SAML connections that have a name that matches the given query, via case-insensitive partial match.
        field :query, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'query', 'style': 'form', 'explode': true } }
        # Sorts organizations memberships by phone_number, email_address, created_at, first_name, last_name or username.
        # By prepending one of those values with + or -,
        # we can choose to sort in ascending (ASC) or descending (DESC) order.
        field :order_by, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'order_by', 'style': 'form', 'explode': true } }
        # Returns SAML connections that have an associated organization ID to the
        # given organizations.
        # For each organization ID, the `+` and `-` can be
        # prepended to the ID, which denote whether the
        # respective organization should be included or
        # excluded from the result set.
        # Accepts up to 100 organization IDs.
        field :organization_id, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'query_param': { 'field_name': 'organization_id', 'style': 'form', 'explode': true } }
        # Applies a limit to the number of results returned.
        # Can be used for paginating the results together with `offset`.
        field :limit, Crystalline::Nilable.new(::Integer), { 'query_param': { 'field_name': 'limit', 'style': 'form', 'explode': true } }
        # Skip the first `offset` results when paginating.
        # Needs to be an integer greater or equal to zero.
        # To be used in conjunction with `limit`.
        field :offset, Crystalline::Nilable.new(::Integer), { 'query_param': { 'field_name': 'offset', 'style': 'form', 'explode': true } }

        
        def initialize(query: nil, order_by: nil, organization_id: nil, limit: 10, offset: 0)
          @query = query
          @order_by = order_by
          @organization_id = organization_id
          @limit = limit
          @offset = offset
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @query == other.query
          return false unless @order_by == other.order_by
          return false unless @organization_id == other.organization_id
          return false unless @limit == other.limit
          return false unless @offset == other.offset
          true
        end
      end
    end
  end
end
