# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations

      class Mapping
        
        include Crystalline::MetadataFields

        # The SCIM group ID from the identity provider.
        field :scim_group_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('scim_group_id'), required: true } }
        # The ID of the organization role to assign to members of the SCIM group.
        field :role_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('role_id'), required: true } }

        
        def initialize(scim_group_id:, role_id:)
          @scim_group_id = scim_group_id
          @role_id = role_id
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @scim_group_id == other.scim_group_id
          return false unless @role_id == other.role_id
          true
        end
      end
    end
  end
end
