# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations
    

      class ReplaceRoleInRoleSetRequest
        
        include Crystalline::MetadataFields

        # The key or ID of the role set
        field :role_set_key_or_id, ::String, { 'path_param': { 'field_name': 'role_set_key_or_id', 'style': 'simple', 'explode': false } }

        field :body, Models::Operations::ReplaceRoleInRoleSetRequestBody, { 'request': { 'media_type': 'application/json' } }

        
        def initialize(role_set_key_or_id:, body:)
          @role_set_key_or_id = role_set_key_or_id
          @body = body
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @role_set_key_or_id == other.role_set_key_or_id
          return false unless @body == other.body
          true
        end
      end
    end
  end
end
