# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations

      class ToggleTemplateDeliveryRequestBody
        
        include Crystalline::MetadataFields

        # Whether Clerk should deliver emails or SMS messages based on the current template
        field :delivered_by_clerk, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('delivered_by_clerk') } }

        
        def initialize(delivered_by_clerk: nil)
          @delivered_by_clerk = delivered_by_clerk
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @delivered_by_clerk == other.delivered_by_clerk
          true
        end
      end
    end
  end
end
