# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations
    

      class UpdateProductionInstanceDomainRequest
        
        include Crystalline::MetadataFields

        # The new home URL of the production instance e.g. https://www.example.com
        field :home_url, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('home_url') } }
        # Whether the domain is a secondary app.
        field :is_secondary, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('is_secondary') } }

        
        def initialize(home_url: nil, is_secondary: nil)
          @home_url = home_url
          @is_secondary = is_secondary
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @home_url == other.home_url
          return false unless @is_secondary == other.is_secondary
          true
        end
      end
    end
  end
end
