# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations

      class UpdateOrganizationMembershipRequest
        
        include Crystalline::MetadataFields

        # The ID of the organization to which this membership belongs
        field :organization_id, ::String, { 'path_param': { 'field_name': 'organization_id', 'style': 'simple', 'explode': false } }
        # The ID of the user to which this membership belongs
        field :user_id, ::String, { 'path_param': { 'field_name': 'user_id', 'style': 'simple', 'explode': false } }

        field :body, Models::Operations::UpdateOrganizationMembershipRequestBody, { 'request': { 'media_type': 'application/json' } }

        
        def initialize(organization_id:, user_id:, body:)
          @organization_id = organization_id
          @user_id = user_id
          @body = body
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @organization_id == other.organization_id
          return false unless @user_id == other.user_id
          return false unless @body == other.body
          true
        end
      end
    end
  end
end
