# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations

      class UpdateInstanceRequest
        
        include Crystalline::MetadataFields

        # For browser-like stacks such as browser extensions, Electron (not officially supported), or Capacitor.js (not officially supported), the instance allowed origins need to be updated with the request origin value. For Chrome extensions popup, background, or service worker pages, the origin is chrome-extension://extension_uuid. For Electron apps the default origin is http://localhost:3000. For Capacitor, the origin is capacitor://localhost.
        field :allowed_origins, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('allowed_origins') } }
        # Toggles test mode for this instance, allowing the use of test email addresses and phone numbers.
        # Defaults to true for development instances.
        field :test_mode, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('test_mode') } }
        # Whether the instance should be using the HIBP service to check passwords for breaches
        field :hibp, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('hibp') } }

        field :support_email, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('support_email') } }

        field :clerk_js_version, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('clerk_js_version') } }

        field :development_origin, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('development_origin') } }
        # Whether the instance should operate in cookieless development mode (i.e. without third-party cookies).
        # Deprecated: Please use `url_based_session_syncing` instead.
        #
        # @deprecated true: This will be removed in a future release, please migrate away from it as soon as possible.
        field :cookieless_dev, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('cookieless_dev') } }
        # Whether the instance should use URL-based session syncing in development mode (i.e. without third-party cookies).
        field :url_based_session_syncing, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('url_based_session_syncing') } }

        
        def initialize(allowed_origins: nil, test_mode: nil, hibp: nil, support_email: nil, clerk_js_version: nil, development_origin: nil, cookieless_dev: nil, url_based_session_syncing: nil)
          @allowed_origins = allowed_origins
          @test_mode = test_mode
          @hibp = hibp
          @support_email = support_email
          @clerk_js_version = clerk_js_version
          @development_origin = development_origin
          @cookieless_dev = cookieless_dev
          @url_based_session_syncing = url_based_session_syncing
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @allowed_origins == other.allowed_origins
          return false unless @test_mode == other.test_mode
          return false unless @hibp == other.hibp
          return false unless @support_email == other.support_email
          return false unless @clerk_js_version == other.clerk_js_version
          return false unless @development_origin == other.development_origin
          return false unless @cookieless_dev == other.cookieless_dev
          return false unless @url_based_session_syncing == other.url_based_session_syncing
          true
        end
      end
    end
  end
end
