# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations

      class UpdateSignUpRequest
        
        include Crystalline::MetadataFields

        # The ID of the sign-up to update
        field :id, ::String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }

        field :body, Crystalline::Nilable.new(Models::Operations::UpdateSignUpRequestBody), { 'request': { 'media_type': 'application/json' } }

        
        def initialize(id:, body: nil)
          @id = id
          @body = body
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @body == other.body
          true
        end
      end
    end
  end
end
