# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations

      class UpdateOrganizationDomainRequestBody
        
        include Crystalline::MetadataFields

        # The enrollment_mode for the new domain. This can be `automatic_invitation`, `automatic_suggestion` or `manual_invitation`
        field :enrollment_mode, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('enrollment_mode') } }
        # The status of the domain's verification
        field :verified, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('verified') } }

        
        def initialize(enrollment_mode: nil, verified: nil)
          @enrollment_mode = enrollment_mode
          @verified = verified
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @enrollment_mode == other.enrollment_mode
          return false unless @verified == other.verified
          true
        end
      end
    end
  end
end
