# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations
    

      class UserPasskeyDeleteRequest
        
        include Crystalline::MetadataFields

        # The ID of the user that owns the passkey identity
        field :user_id, ::String, { 'path_param': { 'field_name': 'user_id', 'style': 'simple', 'explode': false } }
        # The ID of the passkey identity to be deleted
        field :passkey_identification_id, ::String, { 'path_param': { 'field_name': 'passkey_identification_id', 'style': 'simple', 'explode': false } }

        
        def initialize(user_id:, passkey_identification_id:)
          @user_id = user_id
          @passkey_identification_id = passkey_identification_id
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @user_id == other.user_id
          return false unless @passkey_identification_id == other.passkey_identification_id
          true
        end
      end
    end
  end
end
