# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations

      class VerifyM2MTokenBadRequestError
        
        include Crystalline::MetadataFields


        field :message, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('message'), required: true } }

        field :long_message, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('long_message'), required: true } }

        field :code, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('code'), required: true } }

        
        def initialize(message:, long_message:, code:)
          @message = message
          @long_message = long_message
          @code = code
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @message == other.message
          return false unless @long_message == other.long_message
          return false unless @code == other.code
          true
        end
      end
    end
  end
end
