# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Operations

      class VerifyOAuthAccessTokenObject
        include ::Crystalline::Enum
        enums do
          CLERK_IDP_OAUTH_ACCESS_TOKEN = new('clerk_idp_oauth_access_token')
        end
      end
    end
  end
end
