# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration
require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable

# TODO: remove this - temporarily added to pass lint
Metrics/AbcSize:
  Max: 50

# TODO: remove this - temporarily added to pass lint
Metrics/ClassLength:
  Enabled: true
  Max: 160

Metrics/MethodLength:
  Enabled: true
  Max: 50

# TODO: reduce it to 5 - temporarily added to pass lint
Minitest/MultipleAssertions:
  Max: 10

Naming/MethodParameterName:
  AllowedNames: ['pk', 'sk', 'id']

# TODO: remove this - temporarily added to pass lint
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  # If `true`, strings which span multiple lines using `\` for continuation must
  # use the same type of quotes on each line.
  ConsistentQuotesInMultiline: false
