# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # Success
      class AgentTask
        
        include Crystalline::MetadataFields


        field :object, Models::Components::AgentTaskObject, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('object'), required: true, 'decoder': ::Clerk::Utils.enum_from_string(Models::Components::AgentTaskObject, false) } }
        # A stable identifier for the agent, unique per agent_name within an instance.
        #
        field :agent_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('agent_id'), required: true } }
        # A unique identifier for this agent task.
        #
        field :task_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('task_id'), required: true } }
        # The URL that, when visited, creates a session for the user. Only present in the response to a create request.
        #
        field :url, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('url') } }

        
        def initialize(object:, agent_id:, task_id:, url: nil)
          @object = object
          @agent_id = agent_id
          @task_id = task_id
          @url = url
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @object == other.object
          return false unless @agent_id == other.agent_id
          return false unless @task_id == other.task_id
          return false unless @url == other.url
          true
        end
      end
    end
  end
end
