# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class ApplyCommerceDiscountRequest
        
        include Crystalline::MetadataFields

        # The ID of the discount to apply to the subscription item.
        field :discount_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('discount_id'), required: true } }

        
        def initialize(discount_id:)
          @discount_id = discount_id
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @discount_id == other.discount_id
          true
        end
      end
    end
  end
end
