# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class BillingPaymentAttemptProration
        
        include Crystalline::MetadataFields


        field :amount, Models::Components::CommerceMoneyResponse, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('amount'), required: true } }

        field :cycle_days_remaining, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('cycle_days_remaining'), required: true } }

        field :cycle_days_total, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('cycle_days_total'), required: true } }

        field :cycle_remaining_percent, ::Float, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('cycle_remaining_percent'), required: true } }

        
        def initialize(amount:, cycle_days_remaining:, cycle_days_total:, cycle_remaining_percent:)
          @amount = amount
          @cycle_days_remaining = cycle_days_remaining
          @cycle_days_total = cycle_days_total
          @cycle_remaining_percent = cycle_remaining_percent
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @amount == other.amount
          return false unless @cycle_days_remaining == other.cycle_days_remaining
          return false unless @cycle_days_total == other.cycle_days_total
          return false unless @cycle_remaining_percent == other.cycle_remaining_percent
          true
        end
      end
    end
  end
end
