# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class BillingPaymentAttempt
        
        include Crystalline::MetadataFields

        # String representing the object's type. Objects of the same type share the same value.
        field :object, Models::Components::BillingPaymentAttemptObject, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('object'), required: true, 'decoder': ::Clerk::Utils.enum_from_string(Models::Components::BillingPaymentAttemptObject, false) } }
        # Unique identifier for the payment attempt.
        field :id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('id'), required: true } }
        # Unique identifier for the associated payment.
        field :payment_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('payment_id'), required: true } }
        # The ID of the instance this payment attempt belongs to.
        field :instance_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('instance_id'), required: true } }
        # Type of charge for this payment attempt.
        field :charge_type, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('charge_type'), required: true } }
        # Unique identifier for the payee.
        field :payee_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('payee_id'), required: true } }
        # The payee associated with this payment attempt.
        field :payee, Models::Components::Payee, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('payee'), required: true } }
        # Unique identifier for the payer.
        field :payer_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('payer_id'), required: true } }

        field :payer, Models::Components::CommercePayerResponse, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('payer'), required: true } }

        field :amount, Models::Components::CommerceMoneyResponse, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('amount'), required: true } }
        # Unique identifier for the payment method.
        field :payment_method_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('payment_method_id'), required: true } }

        field :payment_method, Models::Components::CommercePaymentMethodResponse, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('payment_method'), required: true } }
        # Unique identifier for the associated statement.
        field :statement_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('statement_id'), required: true } }
        # The current status of the payment attempt.
        field :status, Models::Components::BillingPaymentAttemptStatus, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('status'), required: true, 'decoder': ::Clerk::Utils.enum_from_string(Models::Components::BillingPaymentAttemptStatus, false) } }
        # Unix timestamp (in milliseconds) when the payment attempt was created.
        field :created_at, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('created_at'), required: true } }
        # Unix timestamp (in milliseconds) when the payment attempt was last updated.
        field :updated_at, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('updated_at'), required: true } }
        # Unique identifier for the associated subscription item.
        field :subscription_item_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('subscription_item_id') } }
        # The subscription item associated with this payment attempt.
        field :subscription_item, Crystalline::Nilable.new(Models::Components::SubscriptionItem), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('subscription_item') } }
        # External identifier from the payment gateway.
        field :gateway_external_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('gateway_external_id'), required: true } }
        # External URL from the payment gateway.
        field :gateway_external_url, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('gateway_external_url'), required: true } }
        # Unix timestamp (in milliseconds) when the payment was completed.
        field :paid_at, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('paid_at'), required: true } }
        # Unix timestamp (in milliseconds) when the payment failed to be processed.
        field :failed_at, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('failed_at'), required: true } }

        
        def initialize(object:, id:, payment_id:, instance_id:, charge_type:, payee_id:, payee:, payer_id:, payer:, amount:, payment_method_id:, payment_method:, statement_id:, status:, created_at:, updated_at:, subscription_item_id: nil, subscription_item: nil, gateway_external_id: nil, gateway_external_url: nil, paid_at: nil, failed_at: nil)
          @object = object
          @id = id
          @payment_id = payment_id
          @instance_id = instance_id
          @charge_type = charge_type
          @payee_id = payee_id
          @payee = payee
          @payer_id = payer_id
          @payer = payer
          @amount = amount
          @payment_method_id = payment_method_id
          @payment_method = payment_method
          @statement_id = statement_id
          @status = status
          @created_at = created_at
          @updated_at = updated_at
          @subscription_item_id = subscription_item_id
          @subscription_item = subscription_item
          @gateway_external_id = gateway_external_id
          @gateway_external_url = gateway_external_url
          @paid_at = paid_at
          @failed_at = failed_at
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @object == other.object
          return false unless @id == other.id
          return false unless @payment_id == other.payment_id
          return false unless @instance_id == other.instance_id
          return false unless @charge_type == other.charge_type
          return false unless @payee_id == other.payee_id
          return false unless @payee == other.payee
          return false unless @payer_id == other.payer_id
          return false unless @payer == other.payer
          return false unless @amount == other.amount
          return false unless @payment_method_id == other.payment_method_id
          return false unless @payment_method == other.payment_method
          return false unless @statement_id == other.statement_id
          return false unless @status == other.status
          return false unless @created_at == other.created_at
          return false unless @updated_at == other.updated_at
          return false unless @subscription_item_id == other.subscription_item_id
          return false unless @subscription_item == other.subscription_item
          return false unless @gateway_external_id == other.gateway_external_id
          return false unless @gateway_external_url == other.gateway_external_url
          return false unless @paid_at == other.paid_at
          return false unless @failed_at == other.failed_at
          true
        end
      end
    end
  end
end
