# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class BillingStatement
        
        include Crystalline::MetadataFields

        # String representing the object's type. Objects of the same type share the same value.
        field :object, Models::Components::ObjectCommerceStatement, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('object'), required: true, 'decoder': ::Clerk::Utils.enum_from_string(Models::Components::ObjectCommerceStatement, false) } }
        # Unique identifier for the billing statement.
        field :id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('id'), required: true } }
        # The ID of the instance this statement belongs to.
        field :instance_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('instance_id'), required: true } }
        # Unix timestamp (in milliseconds) when the statement was created.
        field :timestamp, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('timestamp'), required: true } }

        field :payer, Models::Components::CommercePayerResponse, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('payer'), required: true } }
        # The current status of the statement.
        field :status, Models::Components::BillingStatementStatus, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('status'), required: true, 'decoder': ::Clerk::Utils.enum_from_string(Models::Components::BillingStatementStatus, false) } }
        # Totals for the statement.
        field :totals, Models::Components::Totals, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('totals'), required: true } }
        # Array of statement groups.
        field :groups, Crystalline::Array.new(Models::Components::Group), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('groups'), required: true } }

        
        def initialize(object:, id:, instance_id:, timestamp:, payer:, status:, totals:, groups:)
          @object = object
          @id = id
          @instance_id = instance_id
          @timestamp = timestamp
          @payer = payer
          @status = status
          @totals = totals
          @groups = groups
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @object == other.object
          return false unless @id == other.id
          return false unless @instance_id == other.instance_id
          return false unless @timestamp == other.timestamp
          return false unless @payer == other.payer
          return false unless @status == other.status
          return false unless @totals == other.totals
          return false unless @groups == other.groups
          true
        end
      end
    end
  end
end
