# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # BillingPaymentAttemptObject - String representing the object's type. Objects of the same type share the same value.
      class BillingPaymentAttemptObject
        include ::Crystalline::Enum
        enums do
          COMMERCE_PAYMENT = new('commerce_payment')
        end
      end
    end
  end
end
