# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class BillingPaymentAttemptPayer
        
        include Crystalline::MetadataFields


        field :remaining_balance, Models::Components::CommerceMoneyResponse, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('remaining_balance'), required: true } }

        field :applied_amount, Models::Components::CommerceMoneyResponse, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('applied_amount'), required: true } }

        
        def initialize(remaining_balance:, applied_amount:)
          @remaining_balance = remaining_balance
          @applied_amount = applied_amount
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @remaining_balance == other.remaining_balance
          return false unless @applied_amount == other.applied_amount
          true
        end
      end
    end
  end
end
