# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class CommerceSubscriptionNextPayment
        
        include Crystalline::MetadataFields

        # Unix timestamp (milliseconds) of the next payment date.
        field :date, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('date'), required: true } }

        field :amount, Models::Components::CommerceMoneyResponse, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('amount'), required: true } }

        
        def initialize(date:, amount:)
          @date = date
          @amount = amount
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @date == other.date
          return false unless @amount == other.amount
          true
        end
      end
    end
  end
end
