# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # A payer's credit balance.
      class CommerceCreditBalanceResponse
        
        include Crystalline::MetadataFields

        # String representing the object's type. Always "commerce_credit_balance".
        field :object, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('object'), required: true } }
        # The current credit balance. Null when the payer has never had credits.
        field :balance, Crystalline::Nilable.new(Models::Components::Balance), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('balance'), required: true } }

        
        def initialize(object:, balance: nil)
          @object = object
          @balance = balance
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @object == other.object
          return false unless @balance == other.balance
          true
        end
      end
    end
  end
end
