# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # Proration details from passed subscription time
      class CommerceSubscriptionNextPaymentDiscountsProration
        
        include Crystalline::MetadataFields


        field :amount, Models::Components::CommerceMoneyResponse, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('amount'), required: true } }
        # Number of days that have passed in the billing cycle
        field :cycle_days_passed, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('cycle_days_passed'), required: true } }
        # Total number of days in the billing cycle
        field :cycle_days_total, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('cycle_days_total'), required: true } }
        # Percentage of the billing cycle that has passed
        field :cycle_passed_percent, ::Float, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('cycle_passed_percent'), required: true } }

        
        def initialize(amount:, cycle_days_passed:, cycle_days_total:, cycle_passed_percent:)
          @amount = amount
          @cycle_days_passed = cycle_days_passed
          @cycle_days_total = cycle_days_total
          @cycle_passed_percent = cycle_passed_percent
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @amount == other.amount
          return false unless @cycle_days_passed == other.cycle_days_passed
          return false unless @cycle_days_total == other.cycle_days_total
          return false unless @cycle_passed_percent == other.cycle_passed_percent
          true
        end
      end
    end
  end
end
