# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # CommerceDiscountRedemptionResponseStatus - Current status of the discount redemption.
      class CommerceDiscountRedemptionResponseStatus
        include ::Crystalline::Enum
        enums do
          ACTIVE = new('active')
          EXHAUSTED = new('exhausted')
          REMOVED = new('removed')
        end
      end
    end
  end
end
