# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # CommercePriceTransitionResponseObject - String representing the object's type. Objects of the same type share the same value.
      class CommercePriceTransitionResponseObject
        include ::Crystalline::Enum
        enums do
          COMMERCE_PRICE_TRANSITION = new('commerce_price_transition')
        end
      end
    end
  end
end
