# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class CommerceSubscriptionItemAnnualFee
        
        include Crystalline::MetadataFields

        # The amount in cents.
        field :amount, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('amount'), required: true } }
        # The formatted amount as a string (e.g., "$49.99").
        field :amount_formatted, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('amount_formatted'), required: true } }
        # The currency code (e.g., "USD").
        field :currency, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('currency'), required: true } }
        # The currency symbol (e.g., "$").
        field :currency_symbol, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('currency_symbol'), required: true } }

        
        def initialize(amount:, amount_formatted:, currency:, currency_symbol:)
          @amount = amount
          @amount_formatted = amount_formatted
          @currency = currency
          @currency_symbol = currency_symbol
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @amount == other.amount
          return false unless @amount_formatted == other.amount_formatted
          return false unless @currency == other.currency
          return false unless @currency_symbol == other.currency_symbol
          true
        end
      end
    end
  end
end
