# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # CommercePriceResponseObject - String representing the object's type. Objects of the same type share the same value.
      class CommercePriceResponseObject


        include ::Crystalline::Enum

        enums do
          COMMERCE_PRICE = new('commerce_price')
        end
      end
    end
  end
end
