# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # The associated plan.
      class CommerceSubscriptionItemPlan
        
        include Crystalline::MetadataFields

        # String representing the object's type. Objects of the same type share the same value.
        field :object, Models::Components::CommerceSubscriptionItemObjectCommercePlan, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('object'), required: true, 'decoder': ::Clerk::Utils.enum_from_string(Models::Components::CommerceSubscriptionItemObjectCommercePlan, false) } }
        # Unique identifier for the plan.
        field :id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('id'), required: true } }
        # The name of the plan.
        field :name, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('name'), required: true } }

        field :fee, Models::Components::CommerceMoneyResponse, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('fee'), required: true } }
        # The ID of the product this plan belongs to.
        #
        # @deprecated true: This will be removed in a future release, please migrate away from it as soon as possible.
        field :product_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('product_id'), required: true } }
        # Whether this is the default plan.
        field :is_default, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('is_default'), required: true } }
        # Whether this is a recurring plan.
        field :is_recurring, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('is_recurring'), required: true } }
        # Whether this plan is publicly visible.
        field :publicly_visible, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('publicly_visible'), required: true } }
        # Whether this plan has a base fee.
        field :has_base_fee, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('has_base_fee'), required: true } }
        # The payer type this plan is designed for.
        field :for_payer_type, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('for_payer_type'), required: true } }
        # The URL-friendly slug for the plan.
        field :slug, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('slug'), required: true } }
        # Whether free trial is enabled for this plan.
        field :free_trial_enabled, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('free_trial_enabled'), required: true } }

        field :annual_monthly_fee, Crystalline::Nilable.new(Models::Components::CommerceSubscriptionItemAnnualMonthlyFee), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('annual_monthly_fee'), required: true } }

        field :annual_fee, Crystalline::Nilable.new(Models::Components::CommerceSubscriptionItemAnnualFee), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('annual_fee'), required: true } }
        # The description of the plan.
        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('description'), required: true } }
        # The URL of the plan's avatar image.
        field :avatar_url, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('avatar_url'), required: true } }
        # The features included in this plan.
        field :features, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::FeatureResponse)), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('features') } }
        # Number of free trial days for this plan.
        field :free_trial_days, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('free_trial_days'), required: true } }

        
        def initialize(object:, id:, name:, fee:, product_id:, is_default:, is_recurring:, publicly_visible:, has_base_fee:, for_payer_type:, slug:, free_trial_enabled:, annual_monthly_fee: nil, annual_fee: nil, description: nil, avatar_url: nil, features: nil, free_trial_days: nil)
          @object = object
          @id = id
          @name = name
          @fee = fee
          @product_id = product_id
          @is_default = is_default
          @is_recurring = is_recurring
          @publicly_visible = publicly_visible
          @has_base_fee = has_base_fee
          @for_payer_type = for_payer_type
          @slug = slug
          @free_trial_enabled = free_trial_enabled
          @annual_monthly_fee = annual_monthly_fee
          @annual_fee = annual_fee
          @description = description
          @avatar_url = avatar_url
          @features = features
          @free_trial_days = free_trial_days
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @object == other.object
          return false unless @id == other.id
          return false unless @name == other.name
          return false unless @fee == other.fee
          return false unless @product_id == other.product_id
          return false unless @is_default == other.is_default
          return false unless @is_recurring == other.is_recurring
          return false unless @publicly_visible == other.publicly_visible
          return false unless @has_base_fee == other.has_base_fee
          return false unless @for_payer_type == other.for_payer_type
          return false unless @slug == other.slug
          return false unless @free_trial_enabled == other.free_trial_enabled
          return false unless @annual_monthly_fee == other.annual_monthly_fee
          return false unless @annual_fee == other.annual_fee
          return false unless @description == other.description
          return false unless @avatar_url == other.avatar_url
          return false unless @features == other.features
          return false unless @free_trial_days == other.free_trial_days
          true
        end
      end
    end
  end
end
