# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # CookiesObject - String representing the object's type. Objects of the same type share the same value.
      class CookiesObject
        include ::Crystalline::Enum
        enums do
          COOKIES = new('cookies')
        end
      end
    end
  end
end
