# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # The default role assigned to new organization members
      class DefaultRole
        
        include Crystalline::MetadataFields


        field :object, Models::Components::RoleSetObjectRoleSetItem, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('object'), required: true, 'decoder': ::Clerk::Utils.enum_from_string(Models::Components::RoleSetObjectRoleSetItem, false) } }
        # The unique identifier of the role
        field :id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('id'), required: true } }
        # The name of the role
        field :name, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('name'), required: true } }
        # The key of the role (e.g., "org:admin", "org:member")
        field :key, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('key'), required: true } }
        # Unix timestamp of role creation
        field :created_at, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('created_at'), required: true } }
        # Unix timestamp of last role update
        field :updated_at, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('updated_at'), required: true } }
        # Optional description of the role
        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('description'), required: true } }
        # The number of members assigned to this role within the role set
        field :members_count, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('members_count') } }
        # Whether this role has any members assigned within the role set
        field :has_members, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('has_members') } }

        
        def initialize(object:, id:, name:, key:, created_at:, updated_at:, description: nil, members_count: nil, has_members: nil)
          @object = object
          @id = id
          @name = name
          @key = key
          @created_at = created_at
          @updated_at = updated_at
          @description = description
          @members_count = members_count
          @has_members = has_members
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @object == other.object
          return false unless @id == other.id
          return false unless @name == other.name
          return false unless @key == other.key
          return false unless @created_at == other.created_at
          return false unless @updated_at == other.updated_at
          return false unless @description == other.description
          return false unless @members_count == other.members_count
          return false unless @has_members == other.has_members
          true
        end
      end
    end
  end
end
