# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # DirectoryGroupRoleMappingObject - String representing the object's type. Always "directory_group_role_mapping".
      class DirectoryGroupRoleMappingObject
        include ::Crystalline::Enum
        enums do
          DIRECTORY_GROUP_ROLE_MAPPING = new('directory_group_role_mapping')
        end
      end
    end
  end
end
