# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class Domain
        
        include Crystalline::MetadataFields


        field :object, Models::Components::DomainObject, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('object'), required: true, 'decoder': ::Clerk::Utils.enum_from_string(Models::Components::DomainObject, false) } }

        field :id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('id'), required: true } }

        field :name, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('name'), required: true } }

        field :is_satellite, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('is_satellite'), required: true } }

        field :frontend_api_url, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('frontend_api_url'), required: true } }

        field :development_origin, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('development_origin'), required: true } }
        # Null for satellite domains.
        #
        field :accounts_portal_url, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('accounts_portal_url') } }

        field :proxy_url, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('proxy_url') } }

        field :cname_targets, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::CNameTarget)), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('cname_targets') } }

        
        def initialize(object:, id:, name:, is_satellite:, frontend_api_url:, development_origin:, accounts_portal_url: nil, proxy_url: nil, cname_targets: nil)
          @object = object
          @id = id
          @name = name
          @is_satellite = is_satellite
          @frontend_api_url = frontend_api_url
          @development_origin = development_origin
          @accounts_portal_url = accounts_portal_url
          @proxy_url = proxy_url
          @cname_targets = cname_targets
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @object == other.object
          return false unless @id == other.id
          return false unless @name == other.name
          return false unless @is_satellite == other.is_satellite
          return false unless @frontend_api_url == other.frontend_api_url
          return false unless @development_origin == other.development_origin
          return false unless @accounts_portal_url == other.accounts_portal_url
          return false unless @proxy_url == other.proxy_url
          return false unless @cname_targets == other.cname_targets
          true
        end
      end
    end
  end
end
