# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # Effect - The snapshotted discount effect.
      class Effect
        include ::Crystalline::Enum
        enums do
          PERCENTAGE = new('percentage')
          FIXED_AMOUNT = new('fixed_amount')
        end
      end
    end
  end
end
