# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class EmailAddressVerificationSamlStatus
        include ::Crystalline::Enum
        enums do
          UNVERIFIED = new('unverified')
          VERIFIED = new('verified')
          FAILED = new('failed')
          EXPIRED = new('expired')
          TRANSFERABLE = new('transferable')
        end
      end
    end
  end
end
