# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # A URL to initiate an enterprise connection test run
      class EnterpriseConnectionTestRunResponse
        
        include Crystalline::MetadataFields

        # A short-lived URL that can be used to initiate the test run flow
        field :url, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('url'), required: true } }

        
        def initialize(url:)
          @url = url
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @url == other.url
          true
        end
      end
    end
  end
end
