# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class EnterpriseAccountVerificationSamlStrategy
        include ::Crystalline::Enum
        enums do
          SAML = new('saml')
        end
      end
    end
  end
end
