# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # OAuth-specific metadata, present for OIDC connections
      class EnterpriseConnectionTestRunOauth
        
        include Crystalline::MetadataFields


        field :id_token, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('id_token') } }

        field :access_token, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('access_token') } }

        field :user_info, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('user_info') } }

        
        def initialize(id_token: nil, access_token: nil, user_info: nil)
          @id_token = id_token
          @access_token = access_token
          @user_info = user_info
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id_token == other.id_token
          return false unless @access_token == other.access_token
          return false unless @user_info == other.user_info
          true
        end
      end
    end
  end
end
