# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class EnterpriseConnectionObject
        include ::Crystalline::Enum
        enums do
          ENTERPRISE_CONNECTION = new('enterprise_connection')
        end
      end
    end
  end
end
