# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # ExternalAccountWithVerificationObject - String representing the object's type. Objects of the same type share the same value.
      class ExternalAccountWithVerificationObject
        include ::Crystalline::Enum
        enums do
          EXTERNAL_ACCOUNT = new('external_account')
          FACEBOOK_ACCOUNT = new('facebook_account')
          GOOGLE_ACCOUNT = new('google_account')
        end
      end
    end
  end
end
