# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class GoogleOneTap
        
        include Crystalline::MetadataFields


        field :status, Models::Components::VerificationGoogleOneTapStatus, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('status'), required: true, 'decoder': ::Clerk::Utils.enum_from_string(Models::Components::VerificationGoogleOneTapStatus, false) } }

        field :strategy, Models::Components::VerificationGoogleOneTapStrategy, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('strategy'), required: true, 'decoder': ::Clerk::Utils.enum_from_string(Models::Components::VerificationGoogleOneTapStrategy, false) } }

        field :object, Crystalline::Nilable.new(Models::Components::VerificationGoogleOneTapObject), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('object'), 'decoder': ::Clerk::Utils.enum_from_string(Models::Components::VerificationGoogleOneTapObject, true) } }

        field :expire_at, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('expire_at'), required: true } }

        field :attempts, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('attempts'), required: true } }

        field :verified_at_client, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('verified_at_client') } }

        field :error, Crystalline::Nilable.new(Models::Components::VerificationGoogleOneTapClerkError), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('error') } }

        
        def initialize(status:, strategy:, object: nil, expire_at: nil, attempts: nil, verified_at_client: nil, error: nil)
          @status = status
          @strategy = strategy
          @object = object
          @expire_at = expire_at
          @attempts = attempts
          @verified_at_client = verified_at_client
          @error = error
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @status == other.status
          return false unless @strategy == other.strategy
          return false unless @object == other.object
          return false unless @expire_at == other.expire_at
          return false unless @attempts == other.attempts
          return false unless @verified_at_client == other.verified_at_client
          return false unless @error == other.error
          true
        end
      end
    end
  end
end
