# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class IdentificationLink
        
        include Crystalline::MetadataFields


        field :type, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('type'), required: true } }

        field :id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('id'), required: true } }

        
        def initialize(type:, id:)
          @type = type
          @id = id
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @type == other.type
          return false unless @id == other.id
          true
        end
      end
    end
  end
end
