# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class InvitationStatus
        include ::Crystalline::Enum
        enums do
          PENDING = new('pending')
          ACCEPTED = new('accepted')
          REVOKED = new('revoked')
          EXPIRED = new('expired')
        end
      end
    end
  end
end
