# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # Success
      class InvitationRevoked
        
        include Crystalline::MetadataFields


        field :object, Models::Components::InvitationRevokedObject, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('object'), required: true, 'decoder': ::Clerk::Utils.enum_from_string(Models::Components::InvitationRevokedObject, false) } }

        field :id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('id'), required: true } }

        field :email_address, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('email_address'), required: true } }

        field :public_metadata, Crystalline::Hash.new(Symbol, ::Object), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('public_metadata'), required: true } }

        field :status, Models::Components::StatusResponse, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('status'), required: true, 'decoder': ::Clerk::Utils.enum_from_string(Models::Components::StatusResponse, false) } }
        # Unix timestamp of creation.
        #
        field :created_at, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('created_at'), required: true } }
        # Unix timestamp of last update.
        #
        field :updated_at, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('updated_at'), required: true } }

        field :revoked, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('revoked') } }

        field :url, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('url') } }
        # Unix timestamp of expiration.
        #
        field :expires_at, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('expires_at') } }

        
        def initialize(object:, id:, email_address:, public_metadata:, status:, created_at:, updated_at:, revoked: nil, url: nil, expires_at: nil)
          @object = object
          @id = id
          @email_address = email_address
          @public_metadata = public_metadata
          @status = status
          @created_at = created_at
          @updated_at = updated_at
          @revoked = revoked
          @url = url
          @expires_at = expires_at
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @object == other.object
          return false unless @id == other.id
          return false unless @email_address == other.email_address
          return false unless @public_metadata == other.public_metadata
          return false unless @status == other.status
          return false unless @created_at == other.created_at
          return false unless @updated_at == other.updated_at
          return false unless @revoked == other.revoked
          return false unless @url == other.url
          return false unless @expires_at == other.expires_at
          true
        end
      end
    end
  end
end
