# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class Log
        
        include Crystalline::MetadataFields


        field :level, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('level'), required: true } }

        field :message, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('message'), required: true } }

        field :code, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('code') } }

        field :short_message, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('short_message') } }

        
        def initialize(level:, message:, code: nil, short_message: nil)
          @level = level
          @message = message
          @code = code
          @short_message = short_message
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @level == other.level
          return false unless @message == other.message
          return false unless @code == other.code
          return false unless @short_message == other.short_message
          true
        end
      end
    end
  end
end
