# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class MachineScopeObject
        include ::Crystalline::Enum
        enums do
          MACHINE_SCOPE = new('machine_scope')
        end
      end
    end
  end
end
