# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # Machine scope deleted successfully for a machine
      class MachineScopeDeleted
        
        include Crystalline::MetadataFields

        # String representing the object's type.
        field :object, Models::Components::MachineScopeDeletedObject, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('object'), required: true, 'decoder': ::Clerk::Utils.enum_from_string(Models::Components::MachineScopeDeletedObject, false) } }
        # The ID of the machine that had access to the target machine
        field :from_machine_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('from_machine_id'), required: true } }
        # The ID of the machine that was being accessed
        field :to_machine_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('to_machine_id'), required: true } }
        # Whether the machine scope was successfully deleted
        field :deleted, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('deleted'), required: true } }

        
        def initialize(object:, from_machine_id:, to_machine_id:, deleted:)
          @object = object
          @from_machine_id = from_machine_id
          @to_machine_id = to_machine_id
          @deleted = deleted
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @object == other.object
          return false unless @from_machine_id == other.from_machine_id
          return false unless @to_machine_id == other.to_machine_id
          return false unless @deleted == other.deleted
          true
        end
      end
    end
  end
end
