# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # Success
      class OAuthAccessToken
        
        include Crystalline::MetadataFields


        field :object, Models::Components::OAuthAccessTokenObject, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('object'), required: true, 'decoder': ::Clerk::Utils.enum_from_string(Models::Components::OAuthAccessTokenObject, false) } }
        # External account ID
        field :external_account_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('external_account_id'), required: true } }
        # The unique ID of the user in the external provider's system
        field :provider_user_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('provider_user_id'), required: true } }
        # The access token
        field :token, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('token'), required: true } }
        # The ID of the provider
        field :provider, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('provider'), required: true } }

        field :public_metadata, Crystalline::Hash.new(Symbol, ::Object), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('public_metadata'), required: true } }
        # Unix timestamp of the access token expiration.
        field :expires_at, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('expires_at'), required: true } }

        field :label, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('label'), required: true } }
        # The list of scopes that the token is valid for. Only present for OAuth 2.0 tokens.
        field :scopes, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('scopes') } }
        # The ID token retrieved from the OIDC provider. Only present for OIDC-compliant OAuth 2.0 providers when available.
        field :id_token, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('id_token') } }
        # The token secret. Only present for OAuth 1.0 tokens.
        field :token_secret, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('token_secret') } }

        
        def initialize(object:, external_account_id:, provider_user_id:, token:, provider:, public_metadata:, expires_at: nil, label: nil, scopes: nil, id_token: nil, token_secret: nil)
          @object = object
          @external_account_id = external_account_id
          @provider_user_id = provider_user_id
          @token = token
          @provider = provider
          @public_metadata = public_metadata
          @expires_at = expires_at
          @label = label
          @scopes = scopes
          @id_token = id_token
          @token_secret = token_secret
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @object == other.object
          return false unless @external_account_id == other.external_account_id
          return false unless @provider_user_id == other.provider_user_id
          return false unless @token == other.token
          return false unless @provider == other.provider
          return false unless @public_metadata == other.public_metadata
          return false unless @expires_at == other.expires_at
          return false unless @label == other.label
          return false unless @scopes == other.scopes
          return false unless @id_token == other.id_token
          return false unless @token_secret == other.token_secret
          true
        end
      end
    end
  end
end
