# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # Success
      class OrganizationSettings
        
        include Crystalline::MetadataFields

        # String representing the object's type. Objects of the same type share the same value.
        field :object, Models::Components::OrganizationSettingsObject, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('object'), required: true, 'decoder': ::Clerk::Utils.enum_from_string(Models::Components::OrganizationSettingsObject, false) } }

        field :enabled, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('enabled'), required: true } }

        field :max_allowed_memberships, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('max_allowed_memberships'), required: true } }

        field :max_allowed_roles, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('max_allowed_roles'), required: true } }
        # The role key that a user will be assigned after creating an organization.
        field :creator_role, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('creator_role'), required: true } }
        # The default for whether an admin can delete an organization with the Frontend API.
        field :admin_delete_enabled, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('admin_delete_enabled'), required: true } }

        field :domains_enabled, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('domains_enabled'), required: true } }

        field :domains_enrollment_modes, Crystalline::Array.new(Models::Components::DomainsEnrollmentMode), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('domains_enrollment_modes'), required: true } }
        # The role key that it will be used in order to create an organization invitation or suggestion.
        field :domains_default_role, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('domains_default_role'), required: true } }

        field :max_role_sets_allowed, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('max_role_sets_allowed') } }
        # max_allowed_permissions is now a no-op, as permissions are now unlimited
        #
        # @deprecated true: This will be removed in a future release, please migrate away from it as soon as possible.
        field :max_allowed_permissions, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('max_allowed_permissions') } }

        field :slug_disabled, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('slug_disabled') } }
        # The role set key that it will be used to create new organizations.
        field :initial_role_set_key, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('initial_role_set_key') } }

        
        def initialize(object:, enabled:, max_allowed_memberships:, max_allowed_roles:, creator_role:, admin_delete_enabled:, domains_enabled:, domains_enrollment_modes:, domains_default_role:, max_role_sets_allowed: nil, max_allowed_permissions: nil, slug_disabled: nil, initial_role_set_key: nil)
          @object = object
          @enabled = enabled
          @max_allowed_memberships = max_allowed_memberships
          @max_allowed_roles = max_allowed_roles
          @creator_role = creator_role
          @admin_delete_enabled = admin_delete_enabled
          @domains_enabled = domains_enabled
          @domains_enrollment_modes = domains_enrollment_modes
          @domains_default_role = domains_default_role
          @max_role_sets_allowed = max_role_sets_allowed
          @max_allowed_permissions = max_allowed_permissions
          @slug_disabled = slug_disabled
          @initial_role_set_key = initial_role_set_key
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @object == other.object
          return false unless @enabled == other.enabled
          return false unless @max_allowed_memberships == other.max_allowed_memberships
          return false unless @max_allowed_roles == other.max_allowed_roles
          return false unless @creator_role == other.creator_role
          return false unless @admin_delete_enabled == other.admin_delete_enabled
          return false unless @domains_enabled == other.domains_enabled
          return false unless @domains_enrollment_modes == other.domains_enrollment_modes
          return false unless @domains_default_role == other.domains_default_role
          return false unless @max_role_sets_allowed == other.max_role_sets_allowed
          return false unless @max_allowed_permissions == other.max_allowed_permissions
          return false unless @slug_disabled == other.slug_disabled
          return false unless @initial_role_set_key == other.initial_role_set_key
          true
        end
      end
    end
  end
end
