# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # OrganizationDomainObject - String representing the object's type. Objects of the same type share the same value. Always `organization_domain`
      #
      class OrganizationDomainObject
        include ::Crystalline::Enum
        enums do
          ORGANIZATION_DOMAIN = new('organization_domain')
        end
      end
    end
  end
end
