# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class OrganizationWithLogoObject
        include ::Crystalline::Enum
        enums do
          ORGANIZATION = new('organization')
        end
      end
    end
  end
end
