# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class Permission
        
        include Crystalline::MetadataFields


        field :object, Models::Components::PermissionObject, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('object'), required: true, 'decoder': ::Clerk::Utils.enum_from_string(Models::Components::PermissionObject, false) } }

        field :id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('id'), required: true } }

        field :name, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('name'), required: true } }

        field :key, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('key'), required: true } }

        field :description, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('description'), required: true } }

        field :type, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('type'), required: true } }
        # Unix timestamp of creation.
        #
        field :created_at, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('created_at'), required: true } }
        # Unix timestamp of last update.
        #
        field :updated_at, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('updated_at'), required: true } }

        
        def initialize(object:, id:, name:, key:, description:, type:, created_at:, updated_at:)
          @object = object
          @id = id
          @name = name
          @key = key
          @description = description
          @type = type
          @created_at = created_at
          @updated_at = updated_at
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @object == other.object
          return false unless @id == other.id
          return false unless @name == other.name
          return false unless @key == other.key
          return false unless @description == other.description
          return false unless @type == other.type
          return false unless @created_at == other.created_at
          return false unless @updated_at == other.updated_at
          true
        end
      end
    end
  end
end
