# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class PermissionObject
        include ::Crystalline::Enum
        enums do
          PERMISSION = new('permission')
        end
      end
    end
  end
end
