# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # Health check information about a domain's proxy configuration validation attempt.
      class ProxyCheck
        
        include Crystalline::MetadataFields


        field :object, Models::Components::ProxyCheckObject, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('object'), required: true, 'decoder': ::Clerk::Utils.enum_from_string(Models::Components::ProxyCheckObject, false) } }

        field :id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('id'), required: true } }

        field :domain_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('domain_id'), required: true } }

        field :proxy_url, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('proxy_url'), required: true } }

        field :successful, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('successful'), required: true } }
        # Unix timestamp of creation.
        #
        field :created_at, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('created_at'), required: true } }
        # Unix timestamp of last update.
        #
        field :updated_at, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('updated_at'), required: true } }
        # Unix timestamp of last run.
        #
        field :last_run_at, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('last_run_at'), required: true } }

        
        def initialize(object:, id:, domain_id:, proxy_url:, successful:, created_at:, updated_at:, last_run_at: nil)
          @object = object
          @id = id
          @domain_id = domain_id
          @proxy_url = proxy_url
          @successful = successful
          @created_at = created_at
          @updated_at = updated_at
          @last_run_at = last_run_at
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @object == other.object
          return false unless @id == other.id
          return false unless @domain_id == other.domain_id
          return false unless @proxy_url == other.proxy_url
          return false unless @successful == other.successful
          return false unless @created_at == other.created_at
          return false unless @updated_at == other.updated_at
          return false unless @last_run_at == other.last_run_at
          true
        end
      end
    end
  end
end
