# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # Public organization data associated with this domain
      class PublicOrganizationData
        
        include Crystalline::MetadataFields


        field :id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('id'), required: true } }

        field :name, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('name'), required: true } }

        field :slug, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('slug'), required: true } }

        field :has_image, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('has_image'), required: true } }

        field :image_url, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('image_url') } }

        
        def initialize(id:, name:, slug:, has_image:, image_url: nil)
          @id = id
          @name = name
          @slug = slug
          @has_image = has_image
          @image_url = image_url
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @name == other.name
          return false unless @slug == other.slug
          return false unless @has_image == other.has_image
          return false unless @image_url == other.image_url
          true
        end
      end
    end
  end
end
