# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class RecordType
        include ::Crystalline::Enum
        enums do
          CNAME = new('CNAME')
          TXT = new('TXT')
        end
      end
    end
  end
end
