# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class RoleSetObjectRoleSetItem
        include ::Crystalline::Enum
        enums do
          ROLE_SET_ITEM = new('role_set_item')
        end
      end
    end
  end
end
