# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class SAMLConnectionAttributeMapping
        
        include Crystalline::MetadataFields


        field :user_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('user_id'), required: true } }

        field :email_address, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('email_address'), required: true } }

        field :first_name, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('first_name'), required: true } }

        field :last_name, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('last_name'), required: true } }

        
        def initialize(user_id:, email_address:, first_name:, last_name:)
          @user_id = user_id
          @email_address = email_address
          @first_name = first_name
          @last_name = last_name
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @user_id == other.user_id
          return false unless @email_address == other.email_address
          return false unless @first_name == other.first_name
          return false unless @last_name == other.last_name
          true
        end
      end
    end
  end
end
