# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class SchemasCommercePlan
        
        include Crystalline::MetadataFields

        # String representing the object's type. Objects of the same type share the same value.
        field :object, Models::Components::SchemasCommercePlanObject, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('object'), required: true, 'decoder': ::Clerk::Utils.enum_from_string(Models::Components::SchemasCommercePlanObject, false) } }
        # Unique identifier for the commerce plan.
        field :id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('id'), required: true } }
        # The name of the commerce plan.
        field :name, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('name'), required: true } }

        field :fee, Models::Components::CommerceMoneyResponse, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('fee'), required: true } }

        field :annual_monthly_fee, Models::Components::CommerceMoneyResponse, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('annual_monthly_fee'), required: true } }

        field :annual_fee, Models::Components::CommerceMoneyResponse, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('annual_fee'), required: true } }
        # The amount in cents for the plan.
        field :amount, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('amount'), required: true } }
        # The formatted amount as a string (e.g., "$49.99").
        field :amount_formatted, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('amount_formatted'), required: true } }
        # The monthly amount in cents when billed annually.
        field :annual_monthly_amount, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('annual_monthly_amount'), required: true } }
        # The formatted annual monthly amount as a string.
        field :annual_monthly_amount_formatted, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('annual_monthly_amount_formatted'), required: true } }
        # The total annual amount in cents.
        field :annual_amount, ::Integer, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('annual_amount'), required: true } }
        # The formatted annual amount as a string.
        field :annual_amount_formatted, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('annual_amount_formatted'), required: true } }
        # The currency symbol (e.g., "$").
        field :currency_symbol, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('currency_symbol'), required: true } }
        # The currency code (e.g., "USD").
        field :currency, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('currency'), required: true } }
        # The description of the commerce plan.
        field :description, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('description'), required: true } }
        # The ID of the product this plan belongs to.
        field :product_id, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('product_id'), required: true } }
        # Whether this is the default plan.
        field :is_default, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('is_default'), required: true } }
        # Whether this is a recurring plan.
        field :is_recurring, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('is_recurring'), required: true } }
        # Whether this plan is publicly visible.
        field :publicly_visible, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('publicly_visible'), required: true } }
        # Whether this plan has a base fee.
        field :has_base_fee, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('has_base_fee'), required: true } }
        # The types of payers that can use this plan.
        field :payer_type, Crystalline::Array.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('payer_type'), required: true } }
        # The payer type this plan is designed for.
        field :for_payer_type, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('for_payer_type'), required: true } }
        # The URL-friendly slug for the plan.
        field :slug, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('slug'), required: true } }
        # The URL of the plan's avatar image.
        field :avatar_url, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('avatar_url'), required: true } }
        # The features included in this plan.
        field :features, Crystalline::Array.new(Models::Components::SchemasFeatureResponse), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('features'), required: true } }
        # The billing period for the plan.
        field :period, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('period') } }
        # The billing interval.
        field :interval, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('interval') } }
        # Whether free trial is enabled for this plan.
        field :free_trial_enabled, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('free_trial_enabled') } }
        # Number of free trial days for this plan.
        field :free_trial_days, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('free_trial_days') } }

        
        def initialize(object:, id:, name:, fee:, annual_monthly_fee:, annual_fee:, amount:, amount_formatted:, annual_monthly_amount:, annual_monthly_amount_formatted:, annual_amount:, annual_amount_formatted:, currency_symbol:, currency:, description:, product_id:, is_default:, is_recurring:, publicly_visible:, has_base_fee:, payer_type:, for_payer_type:, slug:, avatar_url:, features:, period: nil, interval: nil, free_trial_enabled: nil, free_trial_days: nil)
          @object = object
          @id = id
          @name = name
          @fee = fee
          @annual_monthly_fee = annual_monthly_fee
          @annual_fee = annual_fee
          @amount = amount
          @amount_formatted = amount_formatted
          @annual_monthly_amount = annual_monthly_amount
          @annual_monthly_amount_formatted = annual_monthly_amount_formatted
          @annual_amount = annual_amount
          @annual_amount_formatted = annual_amount_formatted
          @currency_symbol = currency_symbol
          @currency = currency
          @description = description
          @product_id = product_id
          @is_default = is_default
          @is_recurring = is_recurring
          @publicly_visible = publicly_visible
          @has_base_fee = has_base_fee
          @payer_type = payer_type
          @for_payer_type = for_payer_type
          @slug = slug
          @avatar_url = avatar_url
          @features = features
          @period = period
          @interval = interval
          @free_trial_enabled = free_trial_enabled
          @free_trial_days = free_trial_days
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @object == other.object
          return false unless @id == other.id
          return false unless @name == other.name
          return false unless @fee == other.fee
          return false unless @annual_monthly_fee == other.annual_monthly_fee
          return false unless @annual_fee == other.annual_fee
          return false unless @amount == other.amount
          return false unless @amount_formatted == other.amount_formatted
          return false unless @annual_monthly_amount == other.annual_monthly_amount
          return false unless @annual_monthly_amount_formatted == other.annual_monthly_amount_formatted
          return false unless @annual_amount == other.annual_amount
          return false unless @annual_amount_formatted == other.annual_amount_formatted
          return false unless @currency_symbol == other.currency_symbol
          return false unless @currency == other.currency
          return false unless @description == other.description
          return false unless @product_id == other.product_id
          return false unless @is_default == other.is_default
          return false unless @is_recurring == other.is_recurring
          return false unless @publicly_visible == other.publicly_visible
          return false unless @has_base_fee == other.has_base_fee
          return false unless @payer_type == other.payer_type
          return false unless @for_payer_type == other.for_payer_type
          return false unless @slug == other.slug
          return false unless @avatar_url == other.avatar_url
          return false unless @features == other.features
          return false unless @period == other.period
          return false unless @interval == other.interval
          return false unless @free_trial_enabled == other.free_trial_enabled
          return false unless @free_trial_days == other.free_trial_days
          true
        end
      end
    end
  end
end
