# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # SchemasCommerceSubscriptionItemStatus - Current status of the subscription item.
      class SchemasCommerceSubscriptionItemStatus
        include ::Crystalline::Enum
        enums do
          ACTIVE = new('active')
          ENDED = new('ended')
          PAST_DUE = new('past_due')
          UPCOMING = new('upcoming')
          INCOMPLETE = new('incomplete')
          ABANDONED = new('abandoned')
        end
      end
    end
  end
end
