# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # SchemasCommercePlanObject - String representing the object's type. Objects of the same type share the same value.
      class SchemasCommercePlanObject
        include ::Crystalline::Enum
        enums do
          COMMERCE_PLAN = new('commerce_plan')
        end
      end
    end
  end
end
