# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # SCIMDirectoryObject - String representing the object's type. Always "scim_directory".
      class SCIMDirectoryObject
        include ::Crystalline::Enum
        enums do
          SCIM_DIRECTORY = new('scim_directory')
        end
      end
    end
  end
end
