# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # SessionObject - String representing the object's type. Objects of the same type share the same value.
      #
      class SessionObject
        include ::Crystalline::Enum
        enums do
          SESSION = new('session')
        end
      end
    end
  end
end
