# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # StatusCommerceSource - Status of the payment source.
      class StatusCommerceSource
        include ::Crystalline::Enum
        enums do
          ACTIVE = new('active')
          DISCONNECTED = new('disconnected')
        end
      end
    end
  end
end
