# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
    
      # Response that contains a temporary Svix URL to access management dashboard
      class SvixURL
        
        include Crystalline::MetadataFields


        field :svix_url, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('svix_url'), required: true } }

        
        def initialize(svix_url:)
          @svix_url = svix_url
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @svix_url == other.svix_url
          true
        end
      end
    end
  end
end
