# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class Token
        
        include Crystalline::MetadataFields

        # String representing the object's type. Objects of the same type share the same value.
        #
        field :object, Models::Components::TokenObject, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('object'), required: true, 'decoder': ::Clerk::Utils.enum_from_string(Models::Components::TokenObject, false) } }
        # String representing the encoded JSON Web Token (JWT) value.
        #
        field :jwt, ::String, { 'format_json': { 'letter_case': ::Clerk::Utils.field_name('jwt'), required: true } }

        
        def initialize(object:, jwt:)
          @object = object
          @jwt = jwt
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @object == other.object
          return false unless @jwt == other.jwt
          true
        end
      end
    end
  end
end
