# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # TokenObject - String representing the object's type. Objects of the same type share the same value.
      #
      class TokenObject
        include ::Crystalline::Enum
        enums do
          TOKEN = new('token')
        end
      end
    end
  end
end
