# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # TotalCountObject - String representing the object's type. Objects of the same type share the same value.
      #
      class TotalCountObject
        include ::Crystalline::Enum
        enums do
          TOTAL_COUNT = new('total_count')
        end
      end
    end
  end
end
