# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class TrustedDeviceStatus
        include ::Crystalline::Enum
        enums do
          ACTIVE = new('active')
          REVOKED = new('revoked')
        end
      end
    end
  end
end
