# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # Type - The type of the role set ("initial" or "custom")
      class Type
        include ::Crystalline::Enum
        enums do
          INITIAL = new('initial')
          CUSTOM = new('custom')
        end
      end
    end
  end
end
