# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class VerificationPasskeyObject
        include ::Crystalline::Enum
        enums do
          VERIFICATION_PASSKEY = new('verification_passkey')
        end
      end
    end
  end
end
