# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class VerificationGoogleOneTapStrategy
        include ::Crystalline::Enum
        enums do
          GOOGLE_ONE_TAP = new('google_one_tap')
        end
      end
    end
  end
end
