# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components

      class VerificationPasskeyStrategy
        include ::Crystalline::Enum
        enums do
          PASSKEY = new('passkey')
        end
      end
    end
  end
end
