# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module Clerk
  module Models
    module Components
      # Web3WalletObject - String representing the object's type. Objects of the same type share the same value.
      #
      class Web3WalletObject
        include ::Crystalline::Enum
        enums do
          WEB3_WALLET = new('web3_wallet')
        end
      end
    end
  end
end
