workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Clerk-OAS:
        inputs:
            - location: https://raw.githubusercontent.com/clerk/openapi-specs/refs/heads/main/bapi/2025-11-10.yml
        overlays:
            - location: https://raw.githubusercontent.com/clerk/openapi-specs/refs/heads/main/.speakeasy/bapi/fixes.yml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/clerk/clerk/clerk-openapi
targets:
    clerk:
        target: ruby
        source: Clerk-OAS
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/clerk/clerk/clerk-oas-ruby-code-samples
            labelOverride:
                fixedValue: Ruby (SDK)
            blocking: false
