require_relative "resources/allowlist_identifiers"
require_relative "resources/allowlist"
require_relative "resources/clients"
require_relative "resources/emails"
require_relative "resources/sessions"
require_relative "resources/sms_messages"
require_relative "resources/users"
